// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnnifkhoedmnybmfjgeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJubmlma2hvZWRtbnlibWZqZ2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Njc3MzcsImV4cCI6MjA2MDI0MzczN30.UNneoxQ5LkB3_yUNVbHP5D0U1Xwoc-3jfw_4O6zQ1jM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);